# Generated by Django 5.1.3 on 2025-10-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('file', models.FileField(upload_to='ebooks/')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='samples/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publication_date', models.DateField()),
                ('pages', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Negocios', 'Negocios'), ('BestSellers', 'BestSellers'), ('Otros', 'Otros')], default='Otros', max_length=50)),
            ],
        ),
    ]
